### ISSUE TITLE
Signed values reported as unsigned

### ISSUE THREAD

**Issue by HarkonenBade** [cadets/dtrace-scripts#3]
For set{,e,re,res}{u,g}id functions the values of arg_{,r,e,s}{u,g}id is being logged in the cadets json format as unsigned integers, despite the values being signed. This results in values of 2**32 when -1 is supplied as an arg.

**Comment by amstrnad** [comment]
Aha. It looks like gid and uid values are actually stored as unsigned ints. We can handle those specially in audit.d.
